# Use root/example as user/password credentials
version: '3.1'

services:
  server:
    build:
      context: ./server
      dockerfile: ./dev/Dockerfile
    depends_on:
      - mongo
    ports:
      - '4000:4000'
    volumes:
      - ./server:/app
    environment:
      - MONGODB_URI=mongodb://devUser:Password123@mongo:27017/dev
      - PORT=4000
    command: npm run dev

  client:
    build:
      context: ./client
      dockerfile: ./dev/Dockerfile
    depends_on:
      - server
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
    environment:
      - PROXY_HOST=server
      - PROXY_PORT=4000
    command: npm start

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: dev
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: SuperSecret789
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongo-volume:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: SuperSecret789
